name: structured_data_parser
description: A package for parsing structured data embeded in websites.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.3
  html: ^0.15.0
  http: ^1.0.0
  json_annotation: ^4.5.0
  petitparser: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.1.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
